services:
  postgres:
    container_name: postgres
    image: postgres:16.8
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres_test
    ports:
      - "5430:5432"